{{- if .Values.redis.enabled -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.prefix }}-gpc-config
  labels:
    {{- include "go-proxy-cache.labels" . | nindent 4 }}
data:
  config.yml: |
  {{ .Values.goproxycache.config | nindent 4 }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.prefix }}-gpc-redis-config
  labels:
    {{- include "go-proxy-cache.labels" . | nindent 4 }}
data:
  redis.conf: |
  {{ .Values.redis.config | nindent 4 }}
