site_name: fabiocicerchia/go-proxy-cache
repo_url: https://github.com/fabiocicerchia/go-proxy-cache/
site_author: Fabio Cicerchia <info@fabiocicerchia.it>
copyright: Copyright (c) 2020 Fabio Cicerchia info@fabiocicerchia.it
theme:
  name: readthedocs
  highlightjs: true
