apiVersion: v1
entries:
  go-proxy-cache:
  - apiVersion: v2
    appVersion: 1.3.0
    created: "2022-04-07T08:43:22.33892609+02:00"
    description: A Helm chart for Kubernetes
    digest: a1d76006b873bab027f944ba708c9d05bce1007efff0681994d4dc55845ec89f
    name: go-proxy-cache
    type: application
    urls:
    - charts/go-proxy-cache-0.1.0.tgz
    version: 0.1.0
generated: "2022-04-07T08:43:22.336548646+02:00"
