name: Lint Code Base

on: push

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint Code Base
        # TODO: https://github.com/github/super-linter/issues/2255
        uses: docker://github/super-linter:v3.17.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          DOCKERFILE_HADOLINT_FILE_NAME: .hadolint.yml
