name: Docker Builds

on:
  push:
    branches:
      - main
  pull_request:
    type:
      - opened
      - synchronize
  workflow_dispatch: ~

jobs:

  codecov:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Codecov
        continue-on-error: true
        run: bash <(curl -s https://codecov.io/bash)
