name: Builds

on:
  push:
    branches:
      - main
  pull_request:
    type:
      - opened
      - synchronize
  workflow_dispatch: ~

jobs:

  build-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Build
        continue-on-error: true
        run: make build

      - name: Test
        continue-on-error: true
        run: make test

  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Lint
        continue-on-error: true
        run: make lint


  codecov:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Codecov
        continue-on-error: true
        run: make codecov
